name: main

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.*"
      - run: dotnet test -c Release
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.*"
      - run: dotnet pack -c Release --output .
      - run: |
          dotnet nuget push \
          --source https://api.nuget.org/v3/index.json \
          --api-key "$NUGET_TOKEN" \
          *.nupkg
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
